name: kafkaUI-java-build-test  

on:
  push:
    branches: [ master ]  # Trigger condition: When pushing to the master branch
  pull_request:
    branches: [ master ]  # Trigger condition: when a pull request is made for the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Running environment: The latest version of Ubuntu

    steps:
    - uses: actions/checkout@v3  # Check out code
    - name: Set up JDK 17  # Setting up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'maven'

    - name: Build with Maven and Run Tests  # Build the project using Maven
      run: ./mvnw clean install -Pprod

